steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/podlodka-demo:latest"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/podlodka-demo:latest"

images:
  - "gcr.io/$PROJECT_ID/podlodka-demo:latest"

options:
  logging: CLOUD_LOGGING_ONLY
